name: Linters

on: [pull_request]

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
    outputs:
      app: ${{ steps.changes.outputs.app }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            app:
              - 'app/**'
  linters:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.app == 'true'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Get changed files
        id: get-changed-files
        run: |
          echo "changed_files=$(git diff --name-only --diff-filter=dr origin/${{ github.event.pull_request.base.ref }} | grep 'backend/app' | grep '\.py' | tr '\n' ' ')" >> $GITHUB_ENV
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - run: pip install -r ./dev-requirements.txt -r ./requirements.txt
      - name: Black
        if: env.changed_files
        run: black --check --verbose --config=./pyproject.toml ${{env.changed_files}}
      - name: Isort
        if: env.changed_files
        run: isort ${{env.changed_files}} --sp=./pyproject.toml --check-only
      - name: Pylint
        if: env.changed_files
        run: pylint --rcfile=./.pylintrc ${{env.changed_files}}
      - name: Bandit
        if: env.changed_files
        run: bandit -c=./pyproject.toml ${{env.changed_files}}
